// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eywsrmfruiwlgwhkywpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5d3NybWZydWl3bGd3aGt5d3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzY3NTAsImV4cCI6MjA3NzUxMjc1MH0.fzerVJsFXOr3KxGQWihX2oln9ZNk4n3CwSisTM5nJjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});